---
title: "tickfat"
output: html_document
date: "2024-10-08"
---

```{r setup, include=FALSE}

#install packages
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("googlesheets4")) install.packages("googlesheets4")
if (!require("janitor")) install.packages("janitor")
if (!require("lubridate")) install.packages("lubridate")
if (!require("readxl")) install.packages("readxl")
if (!require("MuMIn")) install.packages("MuMIn")
if (!require("MASS")) install.packages("MASS")
if (!require("pscl")) install.packages("pscl")
if (!require("ggokabeito")) install.packages("ggokabeito")
if (!require("remotes")) install.packages("remotes")
#remotes::install_github("trobinj/trtools")

#set working directory to present directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
#load libraries
library(tidyverse)
library(googlesheets4)
library(janitor)
library(lubridate)
library(readxl)
library(MuMIn)
library(MASS)
library(pscl)
library(ggokabeito)
knitr::opts_chunk$set(echo = TRUE)
```
```{r import}
tickfat_data <- read_excel("../data/tickfat_data.xlsx", 
    sheet = "Experiment_2")
View(tickfat_data)
```
```{r data calculations}
df <- tickfat_data |>
  mutate(
    body_fat = pre_wt-post_wt,
    pct_bf = 1-(post_wt/pre_wt), 
    new_tx = case_when(
      tx %in% c("control", "colony") ~ "control", 
      .default = as.character(tx)
    ),
    new_week = case_when(
      week <= 1 ~ 1, 
      .default = week)
    )
  
```
```{r boxplots}
bplot <- df |>
  filter(is.na(comment)) |>
  ggplot(
    aes(x=week, y = body_fat, group = week)
  ) +
  geom_boxplot(aes(fill = sex)) +
  labs(
    title = "body fat (mg)",
    x = "treatment", y = "body fat (mg)",
  ) +
  facet_wrap(~sex)
bplot

bplot2 <- df |>
  filter(is.na(comment)) |>
    group_by(new_week) |>
  ggplot(
    aes(x=as.factor(new_week), y = pct_bf, fill = sex)
  ) +
  geom_boxplot() +
  labs(
    title = "Tick Body Fat",
    x = "week", y = "body fat proportion",
  ) +
  facet_wrap(~new_tx)
bplot2
```

```{r stats}
glm <- glm(body_fat ~ new_week + new_tx + sex, data = df, family = "gaussian")
glm
summary(glm)
```


